name: Log Activities

on:
  push:
    branches:
      - main

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: |
          git fetch --all

      - name: Prepare Change Log
        run: |
          # Create or initialize the changelog.md file
          if [ ! -f changelog.md ]; then
            echo '# Change Log' > changelog.md
            echo 'All notable changes to this project will be documented in this file.' >> changelog.md
            echo '' >> changelog.md
          fi

      - name: Log Commit Message
        run: |
          DATE=$(date +%Y-%m-%d)
          PUSH_ID="${{ github.sha }}"
          COMMENT="${{ github.event.head_commit.message }}"
          COMMITTER="${{ github.event.head_commit.committer.name }}"
          CHANGES="${{ github.event.head_commit.message }}"

          echo "## [$DATE] - $DATE" >> changelog.md
          echo '' >> changelog.md
          echo "### Comment" >> changelog.md
          echo "- $COMMENT" >> changelog.md
          echo '' >> changelog.md
          echo "### Changes" >> changelog.md
          echo "- $CHANGES" >> changelog.md
          echo '' >> changelog.md
          echo "### Committed by" >> changelog.md
          echo "- $COMMITTER" >> changelog.md
          echo '' >> changelog.md
          echo "### Push ID" >> changelog.md
          echo "- $PUSH_ID" >> changelog.md
          echo '' >> changelog.md

      - name: Add and Commit Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add changelog.md
          git commit -m "Update changelog.md" || echo "No changes to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
